### ISSUE TITLE
The whole server needs to be restarted so that a nw client can be added

### ISSUE THREAD

**Issue by bormay** [YunoHost-Apps/wireguard_ynh#49]
The whole server needs to be restarted so that a nw client can be added.
Restarting wireguard via systemctl doesn't work either.

Does anyone else have this issue? Is there something in particular I can restart to add the client without rebooting?

**Comment by tituspijean** [comment]
It's written in the forum thread, in the app's README, and in the logs. Yes, you may need to reboot your server after installing WireGuard, since it adds a module to the Linux kernel.

**Comment by bormay** [comment]
I have to reboot after adding every new client or the new client will not be able to connect. Is there a way around this? Can I restart a particular service instead?

**Comment by tituspijean** [comment]
The service should be automatically restarted, that's strange.

Try, after creating the new client and clicking on `Apply config` in the web UI:
(check at that point if the client works)
```
systemctl restart wireguard_ui
systemctl restart wireguard@wg0.service
```
(check again)

**Comment by Tagadda** [comment]
I can reproduce it.
- Add a new client
- Click `Apply config`
The new client cant' connect
- `systemctl restart wireguard@wg0.service`
The new client can connect.

**Comment by tituspijean** [comment]
There's a `wireguard@wg0.path` service that monitors `/etc/wireguard/wg0.conf` and should take care of restarting `wireguard@wg0.service`... and it does not. 😕

**Comment by Tagadda** [comment]
Ahhh so systemd's path unit dp not **re**start services, but only start them.
We need another service that will be started by the path, and restart the wireguard service accordingly :tired_face:
See https://superuser.com/a/1276457

**Comment by Tagadda** [comment]
Mmmh so I did some tinkering with all this, and I figured that the `wireguard@.path` won't start the `wireguard@.service` because it's already active, due to `RemainAfterExit`. Then if we remove the `RemainAfterExit`, `wireguard@.service` run `ExecStop` right after, so we need to remove `ExecStop` too.
But then, we can't stop the service with `yunohost service stop` anymore.
I think we could integrate to yunohost the `wg-quick@wg0.service` instead of `wireguard@wg0.service`, so we can start and stop the service manually. And only use `wireguard@.service` in the `wireguard@.path`.
